# Generated by Django 4.2 on 2023-06-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='aadsfdff', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
